### recuperar todas las citas

GET http://localhost:1234/citas


### crear una cita

POST http://localhost:1234/citas
Content-Type: application/json

{
  "fecha": "2024-10-10",
  "hora": "11:52:31",
  "paciente": "Mauro el guapo",
  "medico": "Nathy su patrona",
  "consultorio": "420"
}

### Obtener todas las personas
GET http://localhost:1234/persona

### Crear una nueva persona
POST http://localhost:1234/persona
Content-Type: application/json

{
  "id": "123",
  "nombre": "Nath",
  "apellido": "Test",
  "fecha_nacimiento": "1993-07-16",
  "telefono": "123456",
  "email": "nath@test.com"
}