### recuperar todas las citas

GET http://localhost:1234/citas


### crear una cita

POST http://localhost:1234/citas
Content-Type: application/json

{
  "fecha": "2024-10-10",
  "hora": "11:52:31",
  "paciente_id": "Adrian Blanco",
  "medico_id": "Nathalie",
  "consultorio_id": "420",
  "descripcion": "consulta de rutina"
}


### Obtener todas las personas
GET http://localhost:1234/persona

### Crear una nueva persona
POST http://localhost:1234/persona
Content-Type: application/json

{
  "id": "651",
  "nombre": "Adrian",
  "apellido": "Blanco",
  "fecha_nacimiento": "1993-09-18",
  "telefono": "83182887",
  "email": "adri@test.com"
}